feat: general implement
casdoor/casdoor-js-sdk pull request #2
Opened 2021-07-26 05:50 UTC by Zxilly

ref to:
https://github.com/casbin/casbin-oa/blob/master/web/src/auth/Auth.js

Signed-off-by: Zxilly <zhouxinyu1001@gmail.com>

2021-07-26 07:10 UTC, hsluoyz commented
@Kininaru @sh1luo plz review

2021-07-26 11:56 UTC, sh1luo requested changes
I think this pr should be modified into one commit instead of two

2021-07-26 12:35 UTC, Kininaru requested changes

2021-07-26 12:35 UTC, Kininaru commented on src/sdk.ts
> +        const redirectUri = `${window.location.origin}/callback`;
I think the redirect url should be a parameter that users can customize.

2021-07-27 08:14 UTC, hsluoyz commented
@Zxilly we have updated some API names, see: https://github.com/casbin/casbin-oa/commit/d67a3f5263d9c78441675e59da8c5e0a00b3af71

Plz update this PR.

2021-07-28 04:57 UTC, Zxilly commented
@hsluoyz updated

2021-07-29 08:43 UTC, merged