feat: add signinPath to SdkConfig
casdoor/casdoor-js-sdk pull request #35
Opened 2023-02-22 18:44 UTC by xiaocode

Fix: https://github.com/casdoor/casdoor-js-sdk/issues/34

2023-02-22 18:44 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/casdoor/casdoor-js-sdk?pullRequest=35) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/casdoor/casdoor-js-sdk?pullRequest=35) before we can accept your contribution.<br/><hr/>**Admin** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/casdoor/casdoor-js-sdk?pullRequest=35) it.</sub>

2023-02-23 01:32 UTC, hsluoyz commented
@xiaocode use the same committer as your github account, and sign CLA

![image](https://user-images.githubusercontent.com/3787410/220802327-dc76ccc5-ac3a-495a-add6-44fd40f86922.png)

2023-02-23 01:33 UTC, hsluoyz requested changes

2023-02-23 01:33 UTC, hsluoyz commented on src/sdk.ts
> +    signinPath?: string // the path of the signin URL for your Casdoor applcation, will be "/api/signin" if not provided
Also add the new usage to README.md

2023-02-23 04:05 UTC, xiaocode commented on src/sdk.ts
> +    signinPath?: string // the path of the signin URL for your Casdoor applcation, will be "/api/signin" if not provided
I have done that

2023-02-23 04:26 UTC, hsluoyz commented
@xiaocode your committer Email should be added to your GitHub account:

![image](https://user-images.githubusercontent.com/3787410/220821275-cf4ab29a-06e0-48ab-ab4d-d2682e0a1bc8.png)

2023-02-23 04:27 UTC, hsluoyz approved these changes

2023-02-23 05:56 UTC, xiaocode commented
> @xiaocode your committer Email should be added to your GitHub account:
> 
> Also refer to: https://casdoor.org/docs/contributing#modify-prs
> 
> ![image](https://user-images.githubusercontent.com/3787410/220821275-cf4ab29a-06e0-48ab-ab4d-d2682e0a1bc8.png)

Done!

2023-02-23 06:52 UTC, merged